columns_to_use: ['target', 'TaxaDeUtilizacaoDeLinhasNaoGarantidas', 'Idade',
       'NumeroDeVezes30-59DiasAtrasoNaoPior', 'TaxaDeEndividamento',
       'RendaMensal', 'NumeroDeLinhasDeCreditoEEmprestimosAbertos',
       'NumeroDeVezes90DiasAtraso', 'NumeroDeEmprestimosOuLinhasImobiliarias',
       'NumeroDeVezes60-89DiasAtrasoNaoPior', 'NumeroDeDependentes']

train_dataset_name: 'train.csv'
test_dataset_name: 'test.csv'
target_name: 'target'
teste_size: 0.33
random_state: 42
vars_freq_encode: ['faixa_renda_mensal','faixa_numero_dependentes']
model_name: 'model_new.pkl'
